# action.yml
name: "Polytomic Terraform Sync"
description: "Generates Terraform HCL from Polytomic."
branding:
  icon: "archive"
  color: "purple"
inputs:
  api_key:
    description: "Polytomic API key"
    required: true
  output_dir:
    description: "Output directory for exported HCL"
    required: false
    default: "terraform"
  url:
    description: "Polytomic deployment URL"
    required: false
    default: "https://app.polytomic.com"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.output_dir }}
    - ${{ inputs.url }}
